backend:
  name: git-gateway
  branch: DevDevjson

media_folder: "uploads"
public_folder: "/uploads"

collections:
  - name: "articles"
    label: "Recent Articles"
    files:
      - label: "Articles List"
        name: "articles"
        file: "content/articles.json"
        format: "json"
        fields:
          - label: "Articles"
            name: "items"
            widget: "list"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Publication Date", name: "date", widget: "datetime" }
              - { label: "Publication/Source", name: "source", widget: "string" }
              - { label: "Link", name: "link", widget: "string" }
              - { label: "Excerpt (optional)", name: "excerpt", widget: "text", required: false }

  - name: "media"
    label: "Media & Book Reviews"
    files:
      - label: "Media List"
        name: "media"
        file: "content/media.json"
        format: "json"
        fields:
          - label: "Media Items"
            name: "items"
            widget: "list"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Date", name: "date", widget: "datetime" }
              - { label: "Media Outlet/Source", name: "source", widget: "string" }
              - { label: "Link", name: "link", widget: "string" }
              - { label: "Type", name: "type", widget: "select", options: ["Review", "Interview", "Podcast", "TV/Video", "Other"] }
              - { label: "Excerpt (optional)", name: "excerpt", widget: "text", required: false }
